spring:
  application:
    name: storyEndPoint

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update

#  flyway:
#    enabled: true
#    locations: classpath:db/migration   # default location, can change if needed
#    baseline-on-migrate: true           # useful if you already have an existing schema
#    validate-on-migrate: true           # ensures migrations are valid
#    out-of-order: false                 # ensures migrations are applied in order
#    clean-disabled: true
